/* The natural number preprocessing pass.
 *
 * Lift all variables and functions of sort Nat$ to integers,
 * adding non-negativity constraints:
 *   - For each Nat$ variable x, introduce x' : Int and assert x' >= 0.
 *   - For each Nat$ function f, introduce f' over Int and assert
 *       forall x1...xn. (x1 >= 0 /\ ... /\ xn >= 0) => f'(x1,...,xn) >= 0
 *     for each argument/return position that was Nat$.
 * 
 * Parts of the code in nat_to_int.h and nat_to_int.cpp are generated by Claude
 */

#include "cvc5_private.h"

#ifndef CVC5__PREPROCESSING__PASSES__NAT_TO_INT_H
#define CVC5__PREPROCESSING__PASSES__NAT_TO_INT_H

#include <unordered_map>

#include "context/cdhashmap.h"
#include "expr/node.h"
#include "expr/node_manager.h"
#include "preprocessing/preprocessing_pass.h"

namespace cvc5::internal {
namespace preprocessing {
namespace passes {

class NatToInt : public PreprocessingPass
{
  using NodeMap = context::CDHashMap<Node, Node>;

 public:
  NatToInt(PreprocessingPassContext* preprocContext);

 protected:
  PreprocessingPassResult applyInternal(
      AssertionPipeline* assertionsToPreprocess) override;

 private:
  NodeManager* d_nm;
  std::unordered_map<Node, Node> d_varNatToInt;
  std::unordered_map<Node, Node> d_funcNatToInt;
  std::unordered_map<Node, Node> d_lifted;

  bool isNat(const TypeNode& tn) const;

  void collectNatSymbols(TNode root, std::unordered_set<Node>& natVars,
      std::unordered_set<Node>& natFuncs, std::unordered_set<Node>& visited);

  // Recursively create Int analogue for a Nat type node
  TypeNode createIntAnalogue(const TypeNode& tn);
  // Recursively replace every Nat nodes to Int nodes
  Node replaceNatToInt(TNode n);
};

}  // namespace passes
}  // namespace preprocessing
}  // namespace cvc5::internal

#endif /* CVC5__PREPROCESSING__PASSES__NAT_TO_INT_H */
